apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../base]

namespace: penpot

images:
  - name: postgres
    newTag: "18.4-bookworm"
  - name: valkey/valkey
    newTag: "9.1.0-trixie"
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: "v7.15.3"

configMapGenerator:
  - name: params
    behavior: create
    envs:
      - params.env
  - name: oauth2-proxy-config
    behavior: create
    envs:
      - oauth2-proxy.cm.env

secretGenerator:
  - name: postgres-secret
    behavior: replace
    envs:
      - postgres.secret.env
  - name: penpot-secret
    behavior: replace
    envs:
      - penpot.secret.env
  - name: oauth2-proxy-secret
    behavior: create
    envs:
      - oauth2-proxy.secret.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source: { kind: ConfigMap, name: params, fieldPath: data.host }
    targets:
      - select: { kind: Ingress }
        fieldPaths: [spec.rules.0.host, spec.tls.0.hosts.0]

patches:
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: penpot
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
  - target: { kind: StatefulSet, name: postgres }
    patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi
  - target: { kind: PersistentVolumeClaim, name: valkey-data }
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi
