# Consumed by the Helm release, not by any resource in this kustomization
apiVersion: v1
kind: Secret
metadata:
  name: penpot-secret
type: Opaque
stringData:
  PENPOT_SECRET_KEY: placeholdersecretkey
  OIDC_CLIENT_SECRET: placeholderclientsecret
