apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../base]

namespace: open-webui

images:
  - name: ghcr.io/open-webui/open-webui
    newTag: "0.10.2"
  - name: postgres
    newTag: "17.10-bookworm"
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: "v7.15.3"

configMapGenerator:
  - name: params
    behavior: create
    envs:
      - params.env
  - name: openwebui-config
    behavior: replace
    envs:
      - openwebui.cm.env
  - name: oauth2-proxy-config
    behavior: create
    envs:
      - oauth2-proxy.cm.env

secretGenerator:
  - name: postgres-secret
    behavior: replace
    envs:
      - postgres.secret.env
  - name: openwebui-secret
    behavior: replace
    envs:
      - openwebui.secret.env
  - name: oauth2-proxy-secret
    behavior: create
    envs:
      - oauth2-proxy.secret.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source: { kind: ConfigMap, name: params, fieldPath: data.host }
    targets:
      - select: { kind: Ingress }
        fieldPaths: [spec.rules.0.host, spec.tls.0.hosts.0]

patches:
  - patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: open-webui
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
  - target: { kind: StatefulSet, name: postgres } # chats
    patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 2Gi
  - target: { kind: PersistentVolumeClaim, name: openwebui-data } # cache, RAG, files
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 4Gi

